#!/usr/bin/env python

import sys

from rotors_rqt.rotors import Rotors
from rqt_gui.main import Main

plugin = 'rqt_rotors'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
