<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/manipulator_snippets.xacro" />

  <xacro:property name="link_1_width" value="0.04"/>
  <xacro:property name="link_1_height" value="0.008"/>
  <xacro:property name="link_1_length" value="0.24"/>

  <xacro:property name="link_2_width" value="0.04"/>
  <xacro:property name="link_2_height" value="0.008"/>
  <xacro:property name="link_2_length" value="0.35"/>

  <xacro:property name="link_0_width" value="0.04"/>
  <xacro:property name="link_0_height" value="0.0015"/>
  <xacro:property name="link_0_length" value="0.14"/>
  <xacro:property name="link_0_center_to_center_length" value="0.1"/>

  <xacro:property name="end_effector_length" value="0.12"/>
  <xacro:property name="end_effector_radius" value="0.03"/>

  <xacro:property name="link_0_frame">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="link_0_inertia">
    <mass value="0.001"/>
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
      iyy="0.0001" iyz="0.0"
      izz="0.0001"/>
    </xacro:property>

    <xacro:property name="link_2_frame">
      <origin xyz="${link_2_length/2} 0 0" rpy="0 0 0"/>
    </xacro:property>

    <xacro:property name="link_2_inertia">
      <mass value="0.0015"/>
      <inertia ixx="0.00000229511" ixy="0.0" ixz="0.00000000098"
        iyy="0.00018644679" iyz="0.0"
        izz="0.00018419229"/>
      </xacro:property>

      <xacro:property name="link_1_frame">
        <origin xyz="${link_1_length/2} 0 0" rpy="0 0 0"/>
      </xacro:property>

      <xacro:property name="link_1_inertia">
        <mass value="0.0012"/>
        <inertia ixx="0.00000948062" ixy="0.0" ixz="-0.00001716204"
          iyy="0.0000730949" iyz="0.0"
          izz="0.00006364922"/>
        </xacro:property>

        <xacro:property name="end_effector_frame">
          <origin xyz="${end_effector_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:property>

        <xacro:property name="end_effector_inertial">
          <mass value="0.001"/>
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001"/>
          </xacro:property>

          <xacro:property name="end_effector_geometry">
            <geometry>
              <cylinder length="${end_effector_length}"  radius="${end_effector_radius}"/>
            </geometry>
          </xacro:property>


          <!--
          #########################################################################################################################
          Delta manipulator macro:
          #########################################################################################################################
        -->
        <xacro:macro name="delta_manipulator_macro"
          params="namespace parent_link *origin">

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_0"
            parent_link="${namespace}/manipulator_base_link"
            child_link="${namespace}/link_0"
            axis="1 0 0"
            friction="0"
            damping="0.1">
            <origin xyz="0 0 -0.05" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <joint name="mounting_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${namespace}/manipulator_base_link"/>
            <xacro:insert_block name="origin" />
          </joint>

          <!-- Here we define base link of closed kinematic chain -->
          <link name="${namespace}/manipulator_base_link">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_0.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_0.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_0_frame"/>
              <xacro:insert_block name="link_0_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link_0">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_0.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_0.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_0_frame"/>
              <xacro:insert_block name="link_0_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link_1_1">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_1.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_1.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_1_frame"/>
              <xacro:insert_block name="link_1_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link_1_2">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_1_flipped.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_1_flipped.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_1_frame"/>
              <xacro:insert_block name="link_1_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link_2_1">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_2.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_2.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_2_frame"/>
              <xacro:insert_block name="link_2_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/link_2_2">
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_2.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/link_2.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="link_2_frame"/>
              <xacro:insert_block name="link_2_inertia"/>
            </inertial>
          </link>

          <link name="${namespace}/end_effector_link">
            <collision>
              <origin xyz="0 0 -0.015" rpy="0 0 1.2"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/end_effector_plate.dae"/>
              </geometry>
            </collision>
            <visual>
              <origin xyz="0 0 -0.015" rpy="0 0 1.2"/>
              <geometry>
                <mesh filename="package://rotors_description/meshes/delta_manipulator/end_effector_plate.dae"/>
              </geometry>
            </visual>
            <inertial>
              <xacro:insert_block name="end_effector_frame"/>
              <xacro:insert_block name="end_effector_inertial"/>
            </inertial>
          </link>

          <!-- Define joints -->
          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_1"
            parent_link="${namespace}/link_0"
            child_link="${namespace}/link_1_1"
            axis="0 0 1"
            friction="0"
            damping="0.1">
            <origin xyz="${-link_0_center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_2"
            parent_link="${namespace}/link_0"
            child_link="${namespace}/link_1_2"
            axis="0 0 1"
            friction="0"
            damping="0.1">
            <origin xyz="${link_0_center_to_center_length/2} 0 -0.005" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_3"
            parent_link="${namespace}/link_1_1"
            child_link="${namespace}/link_2_1"
            axis="0 0 1"
            friction="0"
            damping="0.1">
            <origin xyz="${link_1_length} 0 0.01" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_4"
            parent_link="${namespace}/link_1_2"
            child_link="${namespace}/link_2_2"
            axis="0 0 1"
            friction="0"
            damping="0.1">
            <origin xyz="${link_1_length} 0 -0.01" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <xacro:gazebo_revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/joint_5"
            parent_link="${namespace}/link_2_1"
            child_link="${namespace}/link_2_2"
            pose="${link_2_length} 0 0 0 0 0"
            axis="0 0 1"
            friction="0"
            damping="0.1"
            spring_reference="0"
            spring_stiffness="0"
            lower_limit="-1e+16"
            upper_limit="1e+16"
            effort_limit="1000">
          </xacro:gazebo_revolute_joint_macro>

          <xacro:revolute_joint_macro
            namespace="${namespace}"
            joint_name="delta_manipulator/end_effector_joint"
            parent_link="${namespace}/link_2_1"
            child_link="${namespace}/end_effector_link"
            axis="0 0 1"
            friction="0"
            damping="0.1">
            <origin xyz="${link_2_length} 0 0" rpy="0 0 0"/>
          </xacro:revolute_joint_macro>

          <!--
          <xacro:fixed_joint_macro
          namespace="${namespace}"
          joint_name="${namespace}/end_effector_joint"
          parent_link="${namespace}/link_2_1"
          child_link="${namespace}/end_effector_link">
          <origin xyz="${link_2_length} 0 0" rpy="0 0 0"/>
        </xacro:fixed_joint_macro>
      -->

      <!-- Attach actuators -->
      <xacro:property name="generic_servo_inertial">
        <inertial>
          <mass value="0.070"/>
          <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0"
            izz="0.001"/>
          </inertial>
        </xacro:property>

        <xacro:servo_motor_macro
          namespace="${namespace}"
          motor_name="joint_1_actuator"
          parent_link="${namespace}/link_0"
          actuated_joint="delta_manipulator/joint_1"
          maxTorque="2"
          noLoadSpeed="0.11"
          Kp="30.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="true"
          visual_scale="1"
          color="Blue">
          <origin xyz="${link_0_center_to_center_length/2} 0 0" rpy="0 0 0"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:servo_motor_macro>

        <xacro:servo_motor_macro
          namespace="${namespace}"
          motor_name="joint_2_actuator"
          parent_link="${namespace}/link_0"
          actuated_joint="delta_manipulator/joint_2"
          maxTorque="2"
          noLoadSpeed="0.11"
          Kp="30.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="true"
          visual_scale="1"
          color="Red">
          <origin xyz="${-link_0_center_to_center_length/2} 0 0" rpy="0 0 0"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:servo_motor_macro>

        <xacro:servo_motor_macro
          namespace="${namespace}"
          motor_name="end_effector_joint_actuator"
          parent_link="${namespace}/link_2_1"
          actuated_joint="delta_manipulator/end_effector_joint"
          maxTorque="0.8"
          noLoadSpeed="0.11"
          Kp="10.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="false"
          visual_scale="1"
          color="Red">
          <origin xyz="${link_2_length} 0 0.02" rpy="-1.57 0 0"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:servo_motor_macro>


        <xacro:servo_motor_macro
          namespace="${namespace}"
          motor_name="joint_0_actuator"
          parent_link="${namespace}/manipulator_base_link"
          actuated_joint="delta_manipulator/joint_0"
          maxTorque="2"
          noLoadSpeed="0.11"
          Kp="30.0"
          Kd="0.05"
          Ki="0.40"
          minAngle="${-pi}"
          maxAngle="${pi}"
          measurement_divisor="1"
          measurement_delay="0"
          unknown_delay="0.0"
          noise_normal_angle="0.0"
          noise_normal_angular_velocity="0.0"
          noise_normal_torque="0.0"
          noise_uniform_angle="0.0"
          noise_uniform_angular_velocity="0.0"
          noise_uniform_torque="0.0"
          enable_visual="true"
          visual_scale="1"
          color="Green">
          <origin xyz="0 0.02 -0.02" rpy="0 1.57 0"/>
          <xacro:insert_block name="generic_servo_inertial"/>
        </xacro:servo_motor_macro>


        <!-- Initial configuration plugin -->
        <gazebo>
          <plugin name="initial_configuration" filename="librotors_gazebo_robot_initial_configuration_plugin.so">
            <robotNamespace>${namespace}</robotNamespace>
            <initial_configuration>
              <config joint_name="delta_manipulator/joint_1"  initial_position="2.488"/>
              <config joint_name="delta_manipulator/joint_3"  initial_position="-1.676"/>
              <config joint_name="delta_manipulator/joint_2" initial_position="0.653"/>
              <config joint_name="delta_manipulator/joint_4" initial_position="1.676"/>
            </initial_configuration>
            <loop_closure_joints>
              <joint joint_name="delta_manipulator/joint_5"/>
            </loop_closure_joints>
          </plugin>
        </gazebo>

        <!-- 6DoF shock absorber plugin -->
        <!-- <gazebo>
          <plugin name="6dof_shock_absorber" filename="librotors_gazebo_six_dof_shock_absorber_plugin.so">
            <robotNamespace>${namespace}</robotNamespace>
            <ParentLinkName>${parent_link} </ParentLinkName>
            <ChildLinkName>${namespace}/r0 </ChildLinkName>
            <translational_spring_constant>10 10 50</translational_spring_constant>
            <translational_damper_constant>5 5 20</translational_damper_constant>
            <rotational_spring_constant>8 15 8</rotational_spring_constant>
            <rotational_damper_constant>1 1 1</rotational_damper_constant>
          </plugin>
        </gazebo> -->

      </xacro:macro>

    </robot>
