#!/usr/bin/env python

import sys

from rqt_rotors.hil_plugin import HilPlugin
from rqt_gui.main import Main

plugin = 'rqt_rotors.hil_plugin.HilPlugin'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
